---
title: "Visualization"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

```{r}
weather_df
```

Let's make a scatterplot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

I always like the dataframe first.

```{r}
gg_temp_scatterplot =
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

gg_temp_scatterplot
```

Let's make this a bit fancier

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, colour = name)) +
  geom_point(aes(colour = name), alpha = .25) +
  geom_smooth(se = FALSE)
```

The aesthetics are up to you.

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(colour = name), alpha = .25) +
  geom_smooth(se = FALSE)

weather_df |>
  ggplot(aes(x = tmin, y = tmax, colour = name)) +
  geom_smooth(se = FALSE)


```

Show faceting

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  facet_grid(. ~ name) # can change to (name ~ .) 横竖变化
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  facet_grid(cols = vars(name)) # 效果同上，只是code变了
```

Let's look at something else.

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, colour = name)) +
  geom_point(aes(size = prcp), alpha = .5) +  # size = prcp: let scatter bigger following the value 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

make a plot of central park tmax v tmin only, and convert temperatures to fahrenheit

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax = tmax * (9/5) +32,
    tmin = tmin * (9/5) +32,
  ) |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
  
```


